./" Manual page for qif2tag
.TH qif2tag 1 "July 18, 1998"
.SH NAME
qif2tag \- Convert a Quicken Interchange Format file into a tag-fintrans file
.SH SYNOPSIS
.B qif2tag

.SH DESCRIPTION
qif2tag takes a Quickend Interchange Format file on standard input and writes
out a tagged financial format file on standard output.


Note that the tagged financial transaction format is described in
 http://www.paladin.demon.co.uk/tag-types/dsc/fintrans.dsc

.SH SEE ALSO
tag2qif(1), tagprogs(1), tag(5)
.SH AUTHOR
John Lines (john@paladin.demon.co.uk)

