.\" Manual page for tag programs
.TH tagprogs 1 "June 17, 1998"
.SH NAME
tagprogs \- utilities for manipulating tagged files

.SH DESCRIPTION

The tag programs are a set of tools which manipulate files in a special
tagged format.

.TP
.B tag2html
Turn a tag file into html

.TP
.B tagextract
Extract selected fields from a tagged file.

.TP
.B tagshow
Show selected files, and totals of field values from a tagged file

.TP
.B tagcount
Count records in a tagged file

.TP
.B tagcheck
Perform integrity checks on a tagged file.



.SH SEE ALSO
tag(5), tab2tag(1), tag2tab(1), tag2html(1), tagextract(1), tagshow(1),
tagcount(1), tagcheck(1)

.SH AUTHOR
John Lines (john@paladin.demon.co.uk)


