./" Manual page for tagsort
.TH tagsort 1 "October 10, 1998
.SH NAME
tagsort \- Sort a tagged file
.SH SYNOPSIS
.B tagsort
.B -r
.B -k fieldname
.B filename

.SH DESCRIPTION

tagsort is a tag aware sort file. It will sort a file of tagged records using
any of the fields as a key.

.SH OPTIONS

.TP
.I -k fieldname
Specifies the field to use as a key.

.TP
.I -r
Sort in reverse order



.SH SEE ALSO
tagprogs(1), tag(5)
.SH AUTHOR
John Lines (john@paladin.demon.co.uk)


